os: linux
dist: trusty
sudo: required
language: python
services: docker

env:
  - PETSC_VERSION=2.3.2

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml)" ]] ||
     (docker build --tag compdatasci/petsc-desktop:$PETSC_VERSION . &&
      docker push compdatasci/petsc-desktop &&
      touch success)'
  - docker images
